app/hits/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class Hit(db.Model):

    __tablename__ = 'hits'

    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(256), unique=True, nullable=False)
    target = db.Column(db.String(128), nullable=False)
    hitman_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    hitman = db.relationship('User', foreign_keys="[Hit.hitman_id]")
    creator_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    creator = db.relationship('User', foreign_keys="[Hit.creator_id]")
    status = db.Column(db.String(255), nullable=False, default="asigned")

    def __init__(self, description, target,hitman_id,creator_id):
        self.description = description
        self.target=target
        self.hitman_id=hitman_id
        self.creator_id=creator_id

    def __repr__(self):
        return f'<Hit {self.target}>'


    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

app/hits/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length
from wtforms.widgets import TextArea

class HitForm(FlaskForm):
    description = StringField('Description', widget=TextArea(), validators=[DataRequired()])
    target = StringField('Target', validators=[DataRequired()])
    assignee = SelectField("Assignee", validators=[DataRequired()])
    submit = SubmitField('Create Hit')

app/hits/__init__.py
from flask import Blueprint
from .models import Hit

hits_bp = Blueprint('hits', __name__, template_folder='templates')

from . import routes

app/hits/routes.py
from flask import (render_template, redirect, url_for,
                   request, current_app,abort)
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from . import hits_bp
from .forms import HitForm
from .models import Hit
from app.auth.models import User


@hits_bp.route("/hits/bulk/", methods=["GET","POST"])
@login_required
def bulk():
    message=""
    hits=[]
    hitmen=[]
    if current_user.id==1:
        hitmen=User.query.filter(User.id>1)
    elif current_user.lackeys:
        hitmen=[x for x in current_user.lackeys ]
    if(current_user.id==1):
        hits=Hit.query.filter(Hit.status=="asigned")
    else:
        for a in current_user.assignments:
            if a.status=="asigned":
                hits.append(a)
        if(current_user.lackeys):
            for lackey in current_user.lackeys:
                for a in lackey.assignments:
                    if a.status=="asigned":
                        hits.append(a)
    if request.method=="POST":
        assignments=request.form.getlist("assignements")
        for a in assignments:
           [hitA,hitmanA] = a.split(",")
           hitAQ=Hit.query.get(hitA)
           hitmanAQ=User.query.get(hitmanA)
           if hitmanAQ.active:
               hitAQ.hitman_id=hitmanA
               hitAQ.save()
        message="Assignes changed succefully"
    return render_template("hits/bulk.html", title="hits",hits=hits,hitmen=hitmen, message=message)

@hits_bp.route("/hits/", methods=["GET"])
@login_required
def list():
    hits=[]
    if(current_user.id==1):
        hits=Hit.query.all()
    else:
        for a in current_user.assignments:
            hits.append(a)
        if(current_user.lackeys):
            for lackey in current_user.lackeys:
                for a in lackey.assignments:
                    hits.append(a)
    return render_template("hits/list.html", title="hits",hits=hits)


@hits_bp.route("/hits/create/", methods=["GET", "POST"])
@login_required
def create():
    if current_user.id != 1:
        print("USER",current_user.id)
        if not current_user.lackeys:
            abort(403)
    form = HitForm()
    hitmen=[]
    if current_user.id==1:
        hitmen=User.query.filter(User.id>1,User.active==True)
    elif current_user.lackeys:
        hitmen=[x for x in current_user.lackeys if x.active ]
    form.assignee.choices=[(x.id, x.name) for x in hitmen]
    if form.validate_on_submit():
        description=form.description.data
        target = form.target.data
        assignee = form.assignee.data
        hit=Hit(description=description,target=target,hitman_id=assignee,creator_id=current_user.id)
        hit.save()
        print("submited",description,target,assignee)
        return redirect(url_for('hits.list'))
    return render_template('hits/create.html', form=form)

@hits_bp.route("/hits/<int:hit_id>/", methods=["GET", "POST"])
@login_required
def detail(hit_id):
    message=""
    hit = Hit.query.get_or_404(hit_id)
    if current_user.id!=1:
        if current_user.id != hit.hitman.manager.id and current_user.id != hit.hitman.id:
            abort(403)
    hitmen=[]
    if current_user.id==1:
        hitmen=User.query.filter(User.id>1)
    elif current_user.lackeys:
        hitmen=current_user.lackeys
    temphitmen=[]
    for hm in hitmen:
        if hm.active == False:
            if hm.id == hit.hitman.id:
                temphitmen.append(hm)
        else:
            temphitmen.append(hm)
    hitmen=temphitmen
    if request.method=="POST":
        status=request.form.get("status")
        assignee = request.form.get("assignee")
        if status in ("success","failed"):
            hit.status=status
            hit.save()
            message="Ended hit succefully"
        if assignee and assignee != current_user.id:
            hassigne=User.get_by_id(assignee)
            if hassigne.active:
                hit.hitman_id=assignee
                message="Change assignee succefully"
                hit.save()
            else:
                message="You can't assign to inactive user"
    return render_template('hits/detail.html', hit=hit,hitmen=hitmen, message=message)

app/hits/templates/hits/bulk.html
{% extends "base_template.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<center>
  <h1>Bulk assignements</h1>
  {% if message %}
  <h3>{{message}}</h3>
  {% endif %}
	<div>
    <form action="" method="POST">
		<table>
			<tr>
				<th>Id</th>
				<th>Target</th>
				<th>Hitman</th>
				<th>Created by</th>
				<th>Status</th>
			</tr>
			{% for hit in hits %}
			<tr>
				<td>{{hit.id}}</td>
				<td>{{hit.target}}</td>
        <td><select name="assignements">
            {% for hitman in hitmen %}
              {% if hitman.active ==False %}
                {% if hit.hitman.id==hitman.id %}
                <option value="{{hit.id}},{{hitman.id}}" {% if hitman.id==hit.hitman.id %} selected="selected" {% endif%}>{{hitman.name}}</option>
                {% endif %}
               {% else %}
                   <option value="{{hit.id}},{{hitman.id}}" {% if hitman.id==hit.hitman.id %} selected="selected" {% endif%}>{{hitman.name}}</option>
               {% endif %}
             {% endfor %}
          </select></td>
				<td>{{hit.creator.name}}</td>
				<td>{{hit.status}}</td>
        <td><a href="{{ url_for('hits.detail', hit_id=hit.id) }}">Detail</a></td>
			</tr>
			{% endfor %}
		</table>
    <input type="submit" value="Save" />
</form>
	</div>
</center>
{% endblock %}

app/hits/templates/hits/create.html
{% extends "base_template.html" %} {% block title %}Login{% endblock %} {% block
content %}
<center>
  <h1>Create hit</h1>
	<div>
		<form action="" method="post" novalidate>
			{{ form.hidden_tag() }}
			<div>
				{{ form.description.label }} {{ form.description(cols="35", rows="20") }}<br />
				{% for error in form.description.errors %}
				<span style="color: red">{{ error }}</span>
				{% endfor %}
			</div>
			<div>
				{{ form.target.label }} {{ form.target }}<br />
				{% for error in form.target.errors %}
				<span style="color: red">{{ error }}</span>
				{% endfor %}
			</div>
			<div>
				{{ form.assignee.label }} {{ form.assignee }}<br />
				{% for error in form.assignee.errors %}
				<span style="color: red">{{ error }}</span>
				{% endfor %}
			</div>
			<div>{{ form.submit() }}</div>
		</form>
	</div>
</center>
{% endblock %}

app/hits/templates/hits/detail.html
{% extends "base_template.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<center>
  <h1>Hit detail</h1>
  {% if message %}
  <h3>{{message}}</h3>
  {% endif %}
	<div>
		<table>
			<tr>
        <td><b>Id:</b></td>
				<td>{{hit.id}}</td>
			</tr>
			<tr>
        <td><b>Target:</b></td>
				<td>{{hit.target}}</td>
			</tr>
			<tr>
        <td><b>Description:</b></td>
				<td>{{hit.description}}</td>
			</tr>
			<tr>
        <td><b>Created by:</b></td>
				<td>{{hit.creator.name}}</td>
			</tr>
      {% if hit.status!='asigned' %}
			<tr>
        <td><b>Status:</b></td>
				<td>{{hit.status}}</td>
			</tr>
			<tr>
        <td><b>Assignee:</b></td>
				<td>{{hit.hitman.name}}</td>
			</tr>
      {% endif%}
		</table>
	</div>
  <form action="" method="POST">
    {% if not current_user.lackeys and current_user.id!=1 and hit.status=='asigned' %}
    <button type="submit" value="success" name="status">Set success</button>
    <button type="submit" value="failed" name="status">Set failed</button>
    {% endif %}
    {% if current_user.lackeys or current_user.id==1 %}
      {% if hit.status=='asigned' %}
      <label>Asignee: 
      <select name="assignee">
        {% for hitman in hitmen %}
        <option value="{{hitman.id}}" {% if hitman.id==hit.hitman.id %} selected="selected" {% endif%} >{{hitman.name}}</option>
        {% endfor %}
      </select></label>
      <input type="submit" value="Save"/>
      {% endif %}
    {% endif %}
  </form>
</center>
{% endblock %}

app/hits/templates/hits/list.html
{% extends "base_template.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<center>
  <h1>Hits</h1>
  {% if current_user.id==1 or current_user.lackeys %}
  <a href="{{ url_for('hits.create') }}">Create Hit</a>
  {% endif %}
	<div>
		<table>
			<tr>
				<th>Id</th>
				<th>Target</th>
				<th>Hitman</th>
				<th>Created by</th>
				<th>Status</th>
			</tr>
			{% for hit in hits %}
			<tr>
				<td>{{hit.id}}</td>
				<td>{{hit.target}}</td>
        <td><a href="{{ url_for('hitmen.detail', hitman_id=hit.hitman.id) }}">{{hit.hitman.name}}</a></td>
				<td>{{hit.creator.name}}</td>
				<td>{{hit.status}}</td>
        <td><a href="{{ url_for('hits.detail', hit_id=hit.id) }}">Detail</a></td>
			</tr>
			{% endfor %}
		</table>
	</div>
</center>
{% endblock %}