app/hitmen/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length


class SignupForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Registrar')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Recuérdame')
    submit = SubmitField('Login')

app/hitmen/__init__.py
from flask import Blueprint

hitmen_bp = Blueprint('hitmen', __name__, template_folder='templates')

from . import routes

app/hitmen/routes.py
from flask import (render_template, redirect, url_for,
                   request, current_app,abort)
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse

from app import login_manager
from . import hitmen_bp
from .forms import SignupForm, LoginForm
from app.auth.models import User


@hitmen_bp.route("/hitmen/", methods=["GET"])
@login_required
def list():
    #  if current_user.is_authenticated:
    #      return redirect(url_for('public.index'))
    hitmen=[]
    if(current_user.id==1):
        hitmen=User.get_all()
    elif(current_user.lackeys):
        hitmen=current_user.lackeys
    else:
        abort(403)
    return render_template("hitmen/list.html",title="Hitmen",hitmen=hitmen)

@hitmen_bp.route("/hitmen/<int:hitman_id>", methods=["GET","POST"])
@login_required
def detail(hitman_id):
    if(current_user.id!=1):
        if hitman_id not in [x.id for x in current_user.lackeys]:
            abort(403)
    message=None
    if(current_user.id==1 or current_user.lackeys):
        hitman=User.get_by_id(hitman_id)
        if(request.method=="POST"):
            save_lackeys=request.form.get("save-lackeys")
            new_lackeys=request.form.getlist("lackeys")
            inactive = request.form.get("inactive-hitman")
            if inactive:
                hitman.active=False
                hitman.save()
                message="Hitman inactived succefully"
            if save_lackeys:
                for l in hitman.lackeys:
                    l.manager=None
                    l.save()
                for nl in new_lackeys:
                    new_lackey=User.get_by_id(nl)
                    new_lackey.manager=hitman
                    new_lackey.save()
                if new_lackeys:
                    message="Lackeys added succefully"
                else:
                    message="Please add some lackeys to hitman"
                if not hitman.active:
                    message="Saved data succefully"
        lackeys = [x.id for x in hitman.lackeys]
        posible_lackeys=[]
        for h in User.get_all():
            if(
                h.id not in lackeys
                and h.id !=1
                and h.id !=hitman.id
                and len(h.lackeys)==0
            ):
                posible_lackeys.append(h)
        return render_template(
            "hitmen/detail.html",
            title="Hitmen",
            hitman=hitman,
            posible_lackeys=posible_lackeys,
            message=message
        )
    else:
        abort(403)

app/hitmen/templates/hitmen/detail.html
{% extends "base_template.html" %} {% block title %}{{title}}{% endblock %} {%
block content %}
<center>
  <h1>Hitman detail</h1>
  {% if message %}
  <h3>{{message}}</h3>
  {% endif %}
  <div>
    <table>
      <tr>
        <td><b>Id</b></td>
        <td>{{hitman.id}}</td>
      </tr>
      <tr>
        <td><b>Name</b></td>
        <td>{{hitman.name}}</td>
      </tr>
      <tr>
        <td><b>Email</b></td>
        <td>{{hitman.email}}</td>
      </tr>
      <tr>
        <td><b>Description</b></td>
        <td>{{hitman.description}}</td>
      </tr>
      {% if hitman.id != 1 %}
      <tr>
        <td><b>Is active: </b></td>
        <form method="post" action="" id="inactive-form">
          <input type="hidden" name="inactive-hitman" value="true" />
          <td>
            {{hitman.active}} {% if hitman.active %}<button
              onclick="inactiveHitman()"
            >
              Inactive hitman</button
            >{% endif %}
          </td>
        </form>
      </tr>
      {% endif %}
    </table>
  </div>
  {% if current_user.id==1 and hitman.id!=1 %}
  <form method="post" action="" id="lackeys-form">
    <div>
      <h3>Lackeys</h3>
      <div id="lackeysDropdown">
        {% for lackey in hitman.lackeys %}
        <div>
          <input
            name="lackeys"
            value="{{lackey.id}}"
            type="checkbox"
            checked
          />
          <label>{{lackey.name}}</label>
        </div>
        {% endfor %}
      </div>
    </div>
    <button type="submit" name="save-lackeys" value="true">Save</button>
  </form>
  <div>
    {% if posible_lackeys %}
    <h3>Possible lackeys</h3>
    <table>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Manager</th>
        <th></th>
      </tr>
      {% for pl in posible_lackeys %}
      <tr>
        <td>{{pl.name}}</td>
        <td>{{pl.email}}</td>
        <td>{{pl.manager.name}}</td>
        <td>
          <a
            href="#"
            onclick="myFunction(event, this,{{ pl.id }}, '{{pl.name}}')"
            >Make lackey</a
          >
        </td>
      </tr>
      {% endfor %} {% endif %}
    </table>
  </div>
  {% endif %}
</center>
<script>
  const lackeysDropdown = document.getElementById("lackeysDropdown");
  function inactiveHitman() {
    let response = confirm("Are you sure?");
    if (response) {
      let inactiveForm = document.getElementById("inactive-form");
      inactiveForm.submit();
    }
  }
  function myFunction(event, el, id, name) {
      {% if hitman.active %}
    event.preventDefault();
    let alackey = document.createElement("input");
    let adiv = document.createElement("div");
    let lackeysForm = document.getElementById("lackeys-form");
    alackey.type = "checkbox";
    alackey.name = "lackeys";
    alackey.value = id;
    alackey.checked = true;
    let alabel = document.createElement("label");
    alabel.innerText = name;
    adiv.appendChild(alackey);
    adiv.appendChild(alabel);
    lackeysDropdown.appendChild(adiv);
    el.parentElement.parentElement.remove();
    let submitButton = document.getElementById("submit");
      {% else %}
      alert("This hitman is inactive")
      {% endif %}
  }
</script>
{% endblock %}

app/hitmen/templates/hitmen/list.html
{% extends "base_template.html" %} {% block title %}{{title}}{% endblock %} {%
block content %}
<center>
  <h1>Hitmen</h1>
	<div>
		<table>
			<tr>
				<th>id</th>
				<th>name</th>
				<th>email</th>
				<th>Hitman type</th>
				<th>Is active</th>
				<th></th>
			</tr>
			{% for hitman in hitmen %}
			<tr>
				<td>{{hitman.id}}</td>
				<td>{{hitman.name}}</td>
				<td>{{hitman.email}}</td>
				{% if hitman.id==1 %}
				<td>Boss</td>
				{% elif hitman.lackeys %}
				<td>Manager</td>
				{% else %}
				<td>Lackey</a></td>
				{% endif %}
        <td>{{hitman.active}}</a></td>
				<td><a href="{{url_for('hitmen.detail', hitman_id=hitman.id)}}">Detail</a></td>
			</tr>
			{% endfor %}
		</table>
	</div>
</center>
{% endblock %}